name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.0', '7.1', '7.2', '7.3', '7.4', '8.0' ]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug2

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Download dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        run: ./vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Upload to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
